//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalSystemEntities : DbContext
    {
        public CarRentalSystemEntities()
            : base("name=CarRentalSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarRentedRecord> CarRentedRecords { get; set; }
        public virtual DbSet<TypeOfCar> TypeOfCars { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<userLogin> userLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
